### ISSUE TITLE
/boot is not automounted, affects system update

### ISSUE THREAD

**Issue by red-hara** [joshskidmore/gpd-micropc-arch-guide#1]
During system update with `pacman -Syu` system failed to create new boot image.
The temporal solution: mount /boot manually and run `mkinitcpio -P`.
The solution for consideration: add proper configuration to `/etc/fstab` ?

**Comment by joshskidmore** [comment]
Thanks for pointing out a potential problem with the guide! I think you may have missed a step; the creation of fstab is handled in the last step of the "Mount, pacstrap and prepare for arch-chroot" section:

    # Generate your fstab
    genfstab -pU /mnt >> /mnt/etc/fstab

That step generates an fstab in the to-be filesystem - including the `/boot` mount.
